// <auto-generated />
using System;
using DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(LinkedNewsDbContext))]
    partial class LinkedNewsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Entities.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("DataLayer.Entities.HubGroup", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Name");

                    b.ToTable("hubGroups");
                });

            modelBuilder.Entity("DataLayer.Entities.HubGroupMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaId")
                        .HasColumnType("int");

                    b.Property<string>("FromUserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GroupChatName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GroupChatName");

                    b.ToTable("hubGroupMessages");
                });

            modelBuilder.Entity("DataLayer.Entities.PrivateChat", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Name");

                    b.ToTable("privateChats");
                });

            modelBuilder.Entity("DataLayer.Entities.UserFriends", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("friend")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("DataLayer.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("GroupName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("DataLayer.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("MessageContent")
                        .HasColumnType("longtext");

                    b.Property<int?>("MessageFromUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MessageTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MessageToGroupGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("MessageToUserUserId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("MessageFromUserId");

                    b.HasIndex("MessageToGroupGroupId");

                    b.HasIndex("MessageToUserUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DataLayer.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BannedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Biography")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<int?>("UnBannedDate")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LinkedNewsChatApp.Hubs.HubMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaId")
                        .HasColumnType("int");

                    b.Property<string>("FromUserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrivateChatName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PrivateChatName");

                    b.ToTable("HubMessages");
                });

            modelBuilder.Entity("LinkedNewsChatApp.Hubs.HubUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("GroupChatName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("GroupChatName");

                    b.ToTable("hubUsers");
                });

            modelBuilder.Entity("DataLayer.Entities.GroupMember", b =>
                {
                    b.HasOne("DataLayer.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("DataLayer.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.HubGroupMessage", b =>
                {
                    b.HasOne("DataLayer.Entities.HubGroup", "hubGroup")
                        .WithMany()
                        .HasForeignKey("GroupChatName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hubGroup");
                });

            modelBuilder.Entity("DataLayer.Message", b =>
                {
                    b.HasOne("DataLayer.User", "MessageFrom")
                        .WithMany()
                        .HasForeignKey("MessageFromUserId");

                    b.HasOne("DataLayer.Group", "MessageToGroup")
                        .WithMany()
                        .HasForeignKey("MessageToGroupGroupId");

                    b.HasOne("DataLayer.User", "MessageToUser")
                        .WithMany()
                        .HasForeignKey("MessageToUserUserId");

                    b.Navigation("MessageFrom");

                    b.Navigation("MessageToGroup");

                    b.Navigation("MessageToUser");
                });

            modelBuilder.Entity("LinkedNewsChatApp.Hubs.HubMessage", b =>
                {
                    b.HasOne("DataLayer.Entities.PrivateChat", "privateChat")
                        .WithMany()
                        .HasForeignKey("PrivateChatName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("privateChat");
                });

            modelBuilder.Entity("LinkedNewsChatApp.Hubs.HubUser", b =>
                {
                    b.HasOne("DataLayer.Entities.HubGroup", "hubGroup")
                        .WithMany()
                        .HasForeignKey("GroupChatName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hubGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
